version: '3.7'

services: 
  nginx: 
    image: nginx:1.16-alpine
    ports: 
      - 5050:80
    volumes: 
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    networks: 
      - frontend_network
      - backend_network
    restart: always

  front_end: 
    build: ./frontend
    env_file: 
      - ./frontend/frontend.env
    volumes: 
      - type: bind
        source: ./frontend/code
        target: /frontend/code
    expose: 
      - 5000
    networks: 
      - backend_network
    container_name: frontend
    entrypoint: npm run dev_server

  picture_gen: 
    build: ./pictureGen
    env_file: 
      - ./pictureGen/pictureGen.env
    volumes: 
      - type: bind
        source: ./pictureGen/code
        target: /pictureGen/code
    expose: 
      - 5000
    networks: 
      - backend_network
      - cache_network
    container_name: pictureGen
    entrypoint: > 
      watchmedo auto-restart --recursive --directory='/app/' python3 /app/pictureGen.py

  horoscope_gen: 
    build: ./horoscopeGen
    env_file: 
      - ./horoscopeGen/horoscopeGen.env
    volumes: 
      - type: bind
        source: ./horoscopeGen/code
        target: /app/
    expose: 
      - 5000
    ports: 
      - 5050:5000
    networks: 
      - backend_network
      - cache_network
    container_name: horoscopeGen
    entrypoint: > 
      watchmedo auto-restart --recursive --directory='/app/' python3 horoscopeGen.py

  redis_cache: 
    image: redis:5-alpine
    expose: 
      - 6379
    volumes: 
      - type: bind 
        source: /tmp/redis
        target: /data
    container_name: redis
    networks:
      - cache_network
  

networks:
  frontend_network:
  backend_network:
  cache_network: